apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - name: netflix
        image: 954108257389.dkr.ecr.us-east-1.amazonaws.com/netflix-app:44
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
