name: Build and Push to ECR

on:
  push:
    branches: [main]

    paths-ignore: [Kubernetes_manifests/**]
    

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
      actions: read

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Set up Docker Buildxx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker image
      run: |
        IMAGE_TAG=${{ github.run_number }}
        IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
        docker build --build-arg TMDB_V3_API_KEY=${{ secrets.TMDB_V3_API_KEY }} -t $IMAGE_URI .
        docker push $IMAGE_URI

    - name: Replace image tag in deployment.yaml
      run: |
        IMAGE_TAG=${{ github.run_number }}
        IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
        sed -i "s|image: .*|image: $IMAGE_URI|" Kubernetes_manifests/deployment.yaml
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV


    - name: Commit updated deployment.yaml
      run: |
           git config user.email "boatengkwasi0303@gmail.com"
           git config user.name "Kwasi B"
           git add Kubernetes_manifests/deployment.yaml
           git commit -m "Update image tag to $IMAGE_TAG"
           git push
