name: Deploy to EKS

on:
  workflow_run:
    workflows: ["Build and Push to ECR"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig \
          --region ${{ secrets.AWS_REGION }} \
          --name ${{ secrets.EKS_CLUSTER_NAME }}

    - name: Create or update regcred for ECR
      run: |
        if ! kubectl get secret regcred --namespace=default; then
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          kubectl create secret docker-registry regcred \
            --docker-server=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com \
            --docker-username=AWS \
            --docker-password-stdin \
            --namespace=default
        else
          echo "regcred already exists"
        fi


    - name: Update tag in Deployment file
      run: |
          sed -i "s|\(image: .*\/kay:\).*|\1${{ github.run_id }}|" Kubernetes_manifests/deployment.yaml

    - name: Deploy to EKS
      run: |
          kubectl apply -f Kubernetes_manifests/deployment.yaml
          kubectl apply -f Kubernetes_manifests/deployment.yaml

