name: Scan Image and Notify

on:
  workflow_run:
    workflows: ["Build and Push to ECR"]
    types:
      - completed

jobs:
  scan:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set image URI
      id: set-image
      run: |
        IMAGE_TAG=${{ github.event.workflow_run.run_number }}
        IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
        echo "::set-output name=image-uri::$IMAGE_URI"

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Trivy Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ steps.set-image.outputs.image-uri }}
        severity: CRITICAL,HIGH
        format: table
        exit-code: 0

    - name: Send Email on Success
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_SENDER }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "✅ Security Scan Passed"
        to: ${{ secrets.EMAIL_RECEIVER }}
        from: GitHub Actions <${{ secrets.EMAIL_SENDER }}>
        body: |
          ✅ Security and code quality scans passed successfully.
          ✅ Image: ${{ steps.get-image.outputs.image-uri }}
