name: Scan Image and Notify

on:
  workflow_run:
    workflows: ["Build and Push to ECR"]
    types:
      - completed

jobs:
  scan:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Trivy Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: $IMAGE_URI
        severity: CRITICAL,HIGH
        format: table
        exit: 0

    - name: Send Email on Success
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_SENDER }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "✅ Security Scan Passed"
        to: ${{ secrets.EMAIL_RECEIVER }}
        from: GitHub Actions <${{ secrets.EMAIL_SENDER }}>
        body: |
          ✅ Security and code quality scans passed successfully.
          ✅ Image: $IMAG_URI
