name: Scan Image and Notify

on:
  workflow_run:
    workflows: ["Build and Push to ECR"]
    types:
      - completed

jobs:
  scan:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}


    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Extract image URI from deployment.yaml
      id: get-image
      run: |
        IMAGE=$(grep 'image:' Kubernetes_manifests/deployment.yaml | awk '{print $2}')
        echo "image-uri=$IMAGE" >> $GITHUB_OUTPUT

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ steps.get-image.outputs.image-uri }}
        format: 'table'
        output: 'trivy-results'
        severity: 'CRITICAL,HIGH'
        exit-code: 0

    - name: Show Trivy Scan Results in GitHub Logs
      run: cat trivy-results
   
    
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    
    - name: Send Email on Success
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_SENDER }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "✅ Security Scan Passed"
        to: ${{ secrets.EMAIL_RECEIVER }}
        from: GitHub Actions <${{ secrets.EMAIL_SENDER }}>
        body: |
          ✅ Security and code quality scans passed successfully.
          ✅ Image: ${{ steps.get-image.outputs.image-uri }}
